apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.shipyard-sockshop-single-stage.svc.cluster.local
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice.shipyard-sockshop-single-stage.svc.cluster.local
